<?php

return [
    ['title' => 'Covent Garden',
    'description' => 'Oggi, primo giorno a Londra, siamo andati a Covent Garden,
                     dove a quanto pare si trova il miglior ufficio di cambio. Ci
                     sono tanti punti d\'interesse, negozi, Starbucks, un\'Apple 
                     Store e la Royal Opera House.',
    'date' => '23-08-2011',
    'image' => '',
    'food' => '',
    'interests' => '',],
    ['title' => '',
    'description' => '',
    'date' => '',
    'image' => '',
    'food' => 'Caffè e cornetti',
    'interests' => 'Starbucks, Apple Store, Royal Opera House',],
    ['title' => 'Buckingham Palace',
    'description' => 'Secondo giorno e si va a vedere il palazzo reale, Buckingham Palace. 
                    Piccolo aggiornamento: non ci hanno fatto passare davanti al palazzo, quindi niente foto con le guardie.',
    'date' => '24-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Gioielli, torta di William a Kate',],
    ['title' => 'Case del Parlamento',
    'description' => 'Siamo andati a vedere le case del parlamento con tanto di Big Ben e abbazia di Westminster.',
    'date' => '25-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Monumento a Newton, tombe di grandi scrittori e dei reali inglesi, il milite ignoto.',],
    ['title' => 'Madame Tussaud',
    'description' => 'Finalmente siamo stati al museo delle cere. Sono persino riuscito a impostare la messa a fuoco automatica, quindi le foto hanno iniziato a venire bene;)',
    'date' => '25-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Statue di celebrità e personaggi, attrazione incentrata su un viaggio nella storia, piano dedicato ai supereroi con tanto di cinema in 4D.',],
    ['title' => 'Windsor',
    'description' => 'Non essendoci lezioni previste per oggi, è stato organizzato un viaggio a Windsor, dove si trova il castello della famiglia reale. Saremmo dovuti andare anche a Eaton, ma la guida ha deciso che non ci fosse niente di interessante lì.',
    'date' => '26-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Residenza dei reali, passeggiata molto lunga, negozio di souvenir.',],
    ['title' => 'Tate Modern',
    'description' => 'Siccome una nostra compagna di gruppo non aveva voglia di vedere cose interessanti, il nostro capogruppo ci ha portato alla Tate Modern. Non avevo mai visto tanta arte moderna tutta insieme. C\'erano anche cose belle qua e là.',
    'date' => '27-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Opere d\'arte moderna',],
    ['title' => 'Portobello',
    'description' => 'Siamo andati a Portobello Market a Notting Hill, sì, lo stesso del film con Andy McDowell e Hugh Grant. Ho trovato delle tavole e dei poster perfetti da regalare alla famiglia. C\'era anche un bellissimo gatto nero col pelo lungo.',
    'date' => '28-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Bancarelle di ogni sorta',],
    ['title' => 'Camden Town',
    'description' => 'La tappa di oggi è Camden Town, dove bisogna stare attenti ai prezzi dei prodotti e riuscire a stare alla larga dagli spacciatori. Ho trovato delle cose molto interessanti, un po\' costose senza motivo;)',
    'date' => '29-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'Negozi',],
    ['title' => 'Cambridge',
    'description' => 'Oggi sotto la pioggia e col freddo che ci mangiava, siamo andati a Cambridge. Abbiamo visto i vari college, uno vicino all\'altro. In città non ho trovato un granché d\'interessante, probabilmente spicca per sobrietà. C\'era un tizio che cantava male Feel di Robbie Williams e una chiesa molto spoglia.',
    'date' => '30-08-2011',
    'image' => '',
    'food' => '',
    'interests' => 'College, chiesa',],
];